// <auto-generated />
using System;
using GymApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GymApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260407201510_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GymApp.Domain.Entities.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MuscleGroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimeConstraint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MuscleGroupId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MuscleGroupId = 1,
                            Name = "Supino reto",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 2,
                            MuscleGroupId = 1,
                            Name = "Supino inclinado",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 3,
                            MuscleGroupId = 1,
                            Name = "Supino declinado",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 4,
                            MuscleGroupId = 1,
                            Name = "Crucifixo reto",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 5,
                            MuscleGroupId = 1,
                            Name = "Cruxifixo inclinado",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 6,
                            MuscleGroupId = 1,
                            Name = "Cross over",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 7,
                            MuscleGroupId = 1,
                            Name = "Peck deck",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 8,
                            MuscleGroupId = 1,
                            Name = "Flexão de braço",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 9,
                            MuscleGroupId = 1,
                            Name = "Pullover",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 10,
                            MuscleGroupId = 1,
                            Name = "Paralela",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 11,
                            MuscleGroupId = 2,
                            Name = "Rosca direta",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 12,
                            MuscleGroupId = 2,
                            Name = "Rosca alternada",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 13,
                            MuscleGroupId = 2,
                            Name = "Rosca martelo",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 14,
                            MuscleGroupId = 2,
                            Name = "Rosca concentrada",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 15,
                            MuscleGroupId = 2,
                            Name = "Rosca scott",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 16,
                            MuscleGroupId = 2,
                            Name = "Rosca 21",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 17,
                            MuscleGroupId = 3,
                            Name = "Tríceps pulley",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 18,
                            MuscleGroupId = 3,
                            Name = "Tríceps corda",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 19,
                            MuscleGroupId = 3,
                            Name = "Tríceps francês",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 20,
                            MuscleGroupId = 3,
                            Name = "Tríceps testa",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 21,
                            MuscleGroupId = 3,
                            Name = "Mergulho",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 22,
                            MuscleGroupId = 3,
                            Name = "Extensão de tríceps",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 23,
                            MuscleGroupId = 3,
                            Name = "Kickback",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 24,
                            MuscleGroupId = 4,
                            Name = "Puxada frontal",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 25,
                            MuscleGroupId = 4,
                            Name = "Puxada posterior",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 26,
                            MuscleGroupId = 4,
                            Name = "Remada curvada",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 27,
                            MuscleGroupId = 4,
                            Name = "Remada unilateral",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 28,
                            MuscleGroupId = 4,
                            Name = "Remada cavalinho",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 29,
                            MuscleGroupId = 4,
                            Name = "Barra fixa",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 30,
                            MuscleGroupId = 4,
                            Name = "Serrote",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 31,
                            MuscleGroupId = 4,
                            Name = "Remada máquina",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 32,
                            MuscleGroupId = 11,
                            Name = "Desenvolvimento com barra",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 33,
                            MuscleGroupId = 11,
                            Name = "Desenvolvimento com halteres",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 34,
                            MuscleGroupId = 11,
                            Name = "Elevação lateral",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 35,
                            MuscleGroupId = 11,
                            Name = "Elevação frontal",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 36,
                            MuscleGroupId = 11,
                            Name = "Encolhimento",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 37,
                            MuscleGroupId = 11,
                            Name = "Cruxifixo invertido",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 38,
                            MuscleGroupId = 11,
                            Name = "Arnold press",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 39,
                            MuscleGroupId = 5,
                            Name = "Abdominal crunch",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 40,
                            MuscleGroupId = 5,
                            Name = "Abdominal infra",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 41,
                            MuscleGroupId = 5,
                            Name = "Prancha",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 42,
                            MuscleGroupId = 5,
                            Name = "Abdominal oblíquo",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 43,
                            MuscleGroupId = 5,
                            Name = "Abdominal máquina",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 44,
                            MuscleGroupId = 5,
                            Name = "Roda abdominal",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 45,
                            MuscleGroupId = 5,
                            Name = "Elevação de pernas",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 46,
                            MuscleGroupId = 6,
                            Name = "Agachamento livre",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 47,
                            MuscleGroupId = 6,
                            Name = "Agachamento hack",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 48,
                            MuscleGroupId = 6,
                            Name = "Leg press",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 49,
                            MuscleGroupId = 6,
                            Name = "Cadeira extensora",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 50,
                            MuscleGroupId = 6,
                            Name = "Avanço",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 51,
                            MuscleGroupId = 6,
                            Name = "Agachamento búlgaro",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 52,
                            MuscleGroupId = 6,
                            Name = "Agachamento sumô",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 53,
                            MuscleGroupId = 7,
                            Name = "Mesa flexora",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 54,
                            MuscleGroupId = 7,
                            Name = "Cadeira flexora",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 55,
                            MuscleGroupId = 7,
                            Name = "Stiff",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 56,
                            MuscleGroupId = 7,
                            Name = "Levantamento terra",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 57,
                            MuscleGroupId = 7,
                            Name = "Agachamento romeno",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 58,
                            MuscleGroupId = 8,
                            Name = "Elevação pélvica",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 59,
                            MuscleGroupId = 8,
                            Name = "Abdução de quadril",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 60,
                            MuscleGroupId = 8,
                            Name = "Kick back glúteo",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 61,
                            MuscleGroupId = 12,
                            Name = "Panturrilha em pé",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 62,
                            MuscleGroupId = 12,
                            Name = "Panturrilha sentado",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 63,
                            MuscleGroupId = 12,
                            Name = "Panturrilha leg press",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 64,
                            MuscleGroupId = 9,
                            Name = "Bom dia",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 65,
                            MuscleGroupId = 9,
                            Name = "Hiperextensão",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 66,
                            MuscleGroupId = 13,
                            Name = "Encolhimento com barra",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 67,
                            MuscleGroupId = 13,
                            Name = "Encolhimento com halteres",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 68,
                            MuscleGroupId = 13,
                            Name = "Remada alta",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 69,
                            MuscleGroupId = 10,
                            Name = "Rosca de punho",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 70,
                            MuscleGroupId = 10,
                            Name = "Rosca de punho invertida",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 71,
                            MuscleGroupId = 10,
                            Name = "Farmer walk",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 72,
                            MuscleGroupId = 10,
                            Name = "Rotação de punho",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 73,
                            MuscleGroupId = 7,
                            Name = "Agachamento smith",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 74,
                            MuscleGroupId = 7,
                            Name = "Flexão nórdica",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 75,
                            MuscleGroupId = 10,
                            Name = "Rosca inversa",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 76,
                            MuscleGroupId = 8,
                            Name = "Afundo",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 77,
                            MuscleGroupId = 4,
                            Name = "Puxada neutra",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 78,
                            MuscleGroupId = 11,
                            Name = "Face pull",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 79,
                            MuscleGroupId = 7,
                            Name = "Stiff unilateral",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 80,
                            MuscleGroupId = 14,
                            Name = "Polichinelo",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 81,
                            MuscleGroupId = 14,
                            Name = "Corrida",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 82,
                            MuscleGroupId = 14,
                            Name = "Caminhada",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 83,
                            MuscleGroupId = 14,
                            Name = "Ciclismo",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 84,
                            MuscleGroupId = 14,
                            Name = "Corda",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 85,
                            MuscleGroupId = 14,
                            Name = "Elíptico",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 87,
                            MuscleGroupId = 14,
                            Name = "Burpee",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 88,
                            MuscleGroupId = 14,
                            Name = "Mountain climber",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 89,
                            MuscleGroupId = 5,
                            Name = "Prancha lateral",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 90,
                            MuscleGroupId = 5,
                            Name = "Prancha com elevação de braço",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 91,
                            MuscleGroupId = 6,
                            Name = "Isometria de agachamento",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 92,
                            MuscleGroupId = 6,
                            Name = "Isometria de avanço",
                            TimeConstraint = "Forbidden"
                        },
                        new
                        {
                            Id = 93,
                            MuscleGroupId = 14,
                            Name = "Escada",
                            TimeConstraint = "Forbidden"
                        });
                });

            modelBuilder.Entity("GymApp.Domain.Entities.ExerciseLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer");

                    b.Property<double>("MaxWeight")
                        .HasColumnType("double precision");

                    b.Property<int>("RepsCompleted")
                        .HasColumnType("integer");

                    b.Property<int>("SetsCompleted")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkoutLogId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutLogId");

                    b.ToTable("ExerciseLogs");
                });

            modelBuilder.Entity("GymApp.Domain.Entities.MuscleGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MuscleGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Peitoral"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bíceps"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tríceps"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Dorsal"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Abdômen"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Quadríceps"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Posterior de Coxa"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Glúteo"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Lombar"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Antebraço"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Ombro"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Panturrilha"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Trapézio"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Cardio"
                        });
                });

            modelBuilder.Entity("GymApp.Domain.Entities.Routine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Routines");
                });

            modelBuilder.Entity("GymApp.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GymApp.Domain.Entities.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoutineId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoutineId");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("GymApp.Domain.Entities.WorkoutExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("IsometricHoldSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("Sets")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("Values")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutExercises");
                });

            modelBuilder.Entity("GymApp.Domain.Entities.WorkoutLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ExecutedAt")
                        .HasColumnType("date");

                    b.Property<Guid?>("WorkoutId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutLogs");
                });

            modelBuilder.Entity("GymApp.Domain.Entities.Exercise", b =>
                {
                    b.HasOne("GymApp.Domain.Entities.MuscleGroup", "MuscleGroup")
                        .WithMany("Exercises")
                        .HasForeignKey("MuscleGroupId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("MuscleGroup");
                });

            modelBuilder.Entity("GymApp.Domain.Entities.ExerciseLog", b =>
                {
                    b.HasOne("GymApp.Domain.Entities.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymApp.Domain.Entities.WorkoutLog", "WorkoutLog")
                        .WithMany("ExercisesLogs")
                        .HasForeignKey("WorkoutLogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutLog");
                });

            modelBuilder.Entity("GymApp.Domain.Entities.Routine", b =>
                {
                    b.HasOne("GymApp.Domain.Entities.User", "User")
                        .WithMany("Routines")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymApp.Domain.Entities.Workout", b =>
                {
                    b.HasOne("GymApp.Domain.Entities.Routine", "Routine")
                        .WithMany("Workouts")
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Routine");
                });

            modelBuilder.Entity("GymApp.Domain.Entities.WorkoutExercise", b =>
                {
                    b.HasOne("GymApp.Domain.Entities.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymApp.Domain.Entities.Workout", "Workout")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("GymApp.Domain.Entities.WorkoutLog", b =>
                {
                    b.HasOne("GymApp.Domain.Entities.Workout", "Workout")
                        .WithMany()
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("GymApp.Domain.Entities.MuscleGroup", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("GymApp.Domain.Entities.Routine", b =>
                {
                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("GymApp.Domain.Entities.User", b =>
                {
                    b.Navigation("Routines");
                });

            modelBuilder.Entity("GymApp.Domain.Entities.Workout", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("GymApp.Domain.Entities.WorkoutLog", b =>
                {
                    b.Navigation("ExercisesLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
