// <auto-generated />
using System;
using GymApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GymApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GymApp.Domain.Entities.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MuscleGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MuscleGroupId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5477b8d4-4a44-47b9-9fe2-ea557cfbb2e9"),
                            MuscleGroupId = new Guid("1d1e3e9b-b392-4fe7-85f0-a3e709408b3c"),
                            Name = "Supino reto"
                        },
                        new
                        {
                            Id = new Guid("299f1eab-49c5-4efe-b06a-9b5a2f0440ce"),
                            MuscleGroupId = new Guid("1d1e3e9b-b392-4fe7-85f0-a3e709408b3c"),
                            Name = "Supino inclinado"
                        },
                        new
                        {
                            Id = new Guid("3d8c2d01-433c-4985-bbc5-340f51725a4f"),
                            MuscleGroupId = new Guid("1d1e3e9b-b392-4fe7-85f0-a3e709408b3c"),
                            Name = "Supino declinado"
                        },
                        new
                        {
                            Id = new Guid("b0383145-066c-4ed9-a86c-b8d7ee70556d"),
                            MuscleGroupId = new Guid("1d1e3e9b-b392-4fe7-85f0-a3e709408b3c"),
                            Name = "Crucifixo reto"
                        },
                        new
                        {
                            Id = new Guid("9377c34f-c7c1-42a5-8fd1-e02245cd4afd"),
                            MuscleGroupId = new Guid("1d1e3e9b-b392-4fe7-85f0-a3e709408b3c"),
                            Name = "Cruxifixo inclinado"
                        },
                        new
                        {
                            Id = new Guid("b4c1132f-063a-44c3-a4cf-6a4e7ae1d42e"),
                            MuscleGroupId = new Guid("1d1e3e9b-b392-4fe7-85f0-a3e709408b3c"),
                            Name = "Cross over"
                        },
                        new
                        {
                            Id = new Guid("477114df-1c1e-4409-a5a3-b6b1f3103e06"),
                            MuscleGroupId = new Guid("1d1e3e9b-b392-4fe7-85f0-a3e709408b3c"),
                            Name = "Peck deck"
                        },
                        new
                        {
                            Id = new Guid("0343986b-3ed0-4484-8da0-3edfd12b3171"),
                            MuscleGroupId = new Guid("1d1e3e9b-b392-4fe7-85f0-a3e709408b3c"),
                            Name = "Flexão de braço"
                        },
                        new
                        {
                            Id = new Guid("e55c80c2-6975-4a82-9c7f-573b3f8724a7"),
                            MuscleGroupId = new Guid("1d1e3e9b-b392-4fe7-85f0-a3e709408b3c"),
                            Name = "Pullover"
                        },
                        new
                        {
                            Id = new Guid("8f67f229-b992-4fe1-9138-2b38309c78b0"),
                            MuscleGroupId = new Guid("1d1e3e9b-b392-4fe7-85f0-a3e709408b3c"),
                            Name = "Paralela"
                        },
                        new
                        {
                            Id = new Guid("258769d6-4554-4b5b-a649-2126233a9b9a"),
                            MuscleGroupId = new Guid("f8f48454-d0ef-4bcf-a75b-5be98be1b838"),
                            Name = "Rosca direta"
                        },
                        new
                        {
                            Id = new Guid("82c2de4a-7eb7-4ab7-bb71-ec7a2099fdef"),
                            MuscleGroupId = new Guid("f8f48454-d0ef-4bcf-a75b-5be98be1b838"),
                            Name = "Rosca alternada"
                        },
                        new
                        {
                            Id = new Guid("1c4b35e5-39d8-49bc-a5d3-e736e280a307"),
                            MuscleGroupId = new Guid("f8f48454-d0ef-4bcf-a75b-5be98be1b838"),
                            Name = "Rosca martelo"
                        },
                        new
                        {
                            Id = new Guid("fc6fe802-24e7-40a9-9129-2330f841bb2d"),
                            MuscleGroupId = new Guid("f8f48454-d0ef-4bcf-a75b-5be98be1b838"),
                            Name = "Rosca concentrada"
                        },
                        new
                        {
                            Id = new Guid("d0957c87-4dd4-4875-af14-ca95ac63daa0"),
                            MuscleGroupId = new Guid("f8f48454-d0ef-4bcf-a75b-5be98be1b838"),
                            Name = "Rosca scott"
                        },
                        new
                        {
                            Id = new Guid("4f7cbc31-77e2-4a6a-aee0-5705cb347a40"),
                            MuscleGroupId = new Guid("f8f48454-d0ef-4bcf-a75b-5be98be1b838"),
                            Name = "Rosca 21"
                        },
                        new
                        {
                            Id = new Guid("c3b7ac18-e8dc-4a37-b401-ec994fe10fa0"),
                            MuscleGroupId = new Guid("9c4260d8-b1d6-4fd9-8dd4-b3ecae2f3dc7"),
                            Name = "Tríceps pulley"
                        },
                        new
                        {
                            Id = new Guid("06bf2570-ba26-4059-9410-cc170f68ee95"),
                            MuscleGroupId = new Guid("9c4260d8-b1d6-4fd9-8dd4-b3ecae2f3dc7"),
                            Name = "Tríceps corda"
                        },
                        new
                        {
                            Id = new Guid("dd2d045d-0753-4305-9270-31911a449bb0"),
                            MuscleGroupId = new Guid("9c4260d8-b1d6-4fd9-8dd4-b3ecae2f3dc7"),
                            Name = "Tríceps francês"
                        },
                        new
                        {
                            Id = new Guid("bfe35d53-8096-4564-ae6d-9836f6ba0fb4"),
                            MuscleGroupId = new Guid("9c4260d8-b1d6-4fd9-8dd4-b3ecae2f3dc7"),
                            Name = "Tríceps testa"
                        },
                        new
                        {
                            Id = new Guid("b858030a-9820-4b69-91ef-2b3e83f97f56"),
                            MuscleGroupId = new Guid("9c4260d8-b1d6-4fd9-8dd4-b3ecae2f3dc7"),
                            Name = "Mergulho"
                        },
                        new
                        {
                            Id = new Guid("34c46b1b-50e9-4aee-a279-e98c77531aa1"),
                            MuscleGroupId = new Guid("9c4260d8-b1d6-4fd9-8dd4-b3ecae2f3dc7"),
                            Name = "Extensão de tríceps"
                        },
                        new
                        {
                            Id = new Guid("dbc68a4c-a5f6-42e0-89cc-35b188179702"),
                            MuscleGroupId = new Guid("9c4260d8-b1d6-4fd9-8dd4-b3ecae2f3dc7"),
                            Name = "Kickback"
                        },
                        new
                        {
                            Id = new Guid("284e04e3-48ca-4119-8fa8-df1ad5713f14"),
                            MuscleGroupId = new Guid("bd5b2d35-2696-4777-a49e-88ccdff78295"),
                            Name = "Puxada frontal"
                        },
                        new
                        {
                            Id = new Guid("bec6de7c-3298-4b63-ac7a-4615be4ba051"),
                            MuscleGroupId = new Guid("bd5b2d35-2696-4777-a49e-88ccdff78295"),
                            Name = "Puxada posterior"
                        },
                        new
                        {
                            Id = new Guid("12623ed5-5b3c-4c55-b3d5-a3e118c7e3a8"),
                            MuscleGroupId = new Guid("bd5b2d35-2696-4777-a49e-88ccdff78295"),
                            Name = "Remada curvada"
                        },
                        new
                        {
                            Id = new Guid("e3091c87-603a-446b-9955-14870f0b1990"),
                            MuscleGroupId = new Guid("bd5b2d35-2696-4777-a49e-88ccdff78295"),
                            Name = "Remada unilateral"
                        },
                        new
                        {
                            Id = new Guid("3077eb86-f92c-4889-8616-3d1ff3b688f8"),
                            MuscleGroupId = new Guid("bd5b2d35-2696-4777-a49e-88ccdff78295"),
                            Name = "Remada cavalinho"
                        },
                        new
                        {
                            Id = new Guid("50ac7d47-2056-4d40-9066-c78be66a9d25"),
                            MuscleGroupId = new Guid("bd5b2d35-2696-4777-a49e-88ccdff78295"),
                            Name = "Barra fixa"
                        },
                        new
                        {
                            Id = new Guid("2682d649-a454-4a62-a207-ad27411d3edb"),
                            MuscleGroupId = new Guid("bd5b2d35-2696-4777-a49e-88ccdff78295"),
                            Name = "Serrote"
                        },
                        new
                        {
                            Id = new Guid("29d94801-2fa9-4d0f-b349-6010b5406e0b"),
                            MuscleGroupId = new Guid("bd5b2d35-2696-4777-a49e-88ccdff78295"),
                            Name = "Remada máquina"
                        },
                        new
                        {
                            Id = new Guid("d3e8f290-2f5f-4516-8572-d00092be022d"),
                            MuscleGroupId = new Guid("4e69d837-ae32-4272-9908-341963a08314"),
                            Name = "Desenvolvimento com barra"
                        },
                        new
                        {
                            Id = new Guid("139825e7-ffe4-4699-9c66-0064a60b1dcb"),
                            MuscleGroupId = new Guid("4e69d837-ae32-4272-9908-341963a08314"),
                            Name = "Desenvolvimento com halteres"
                        },
                        new
                        {
                            Id = new Guid("edcfaacd-e229-4248-85c6-c66212206557"),
                            MuscleGroupId = new Guid("4e69d837-ae32-4272-9908-341963a08314"),
                            Name = "Elevação lateral"
                        },
                        new
                        {
                            Id = new Guid("0c6ddb57-8c8c-4412-90fa-cdf2107be429"),
                            MuscleGroupId = new Guid("4e69d837-ae32-4272-9908-341963a08314"),
                            Name = "Elevação frontal"
                        },
                        new
                        {
                            Id = new Guid("cf12543e-2251-44ab-b7a1-9aa5ee0e87b6"),
                            MuscleGroupId = new Guid("4e69d837-ae32-4272-9908-341963a08314"),
                            Name = "Encolhimento"
                        },
                        new
                        {
                            Id = new Guid("4719f42c-9f84-4e04-b08c-8e8606d2c370"),
                            MuscleGroupId = new Guid("4e69d837-ae32-4272-9908-341963a08314"),
                            Name = "Cruxifixo invertido"
                        },
                        new
                        {
                            Id = new Guid("4c4cc220-e1e3-4091-9ebc-24c97f0add93"),
                            MuscleGroupId = new Guid("4e69d837-ae32-4272-9908-341963a08314"),
                            Name = "Arnold press"
                        },
                        new
                        {
                            Id = new Guid("185263d5-95c0-41da-8973-cf2d7c34d5c9"),
                            MuscleGroupId = new Guid("ea069203-b519-4629-bee7-e7a07ad1f1b4"),
                            Name = "Abdominal crunch"
                        },
                        new
                        {
                            Id = new Guid("02e88224-85c3-4c27-9526-5f4dfd70ab20"),
                            MuscleGroupId = new Guid("ea069203-b519-4629-bee7-e7a07ad1f1b4"),
                            Name = "Abdominal infra"
                        },
                        new
                        {
                            Id = new Guid("fd126882-b03b-4337-93a9-df121adef819"),
                            MuscleGroupId = new Guid("ea069203-b519-4629-bee7-e7a07ad1f1b4"),
                            Name = "Prancha"
                        },
                        new
                        {
                            Id = new Guid("709e7f4c-12d5-4461-aceb-fe626b89f1a6"),
                            MuscleGroupId = new Guid("ea069203-b519-4629-bee7-e7a07ad1f1b4"),
                            Name = "Abdominal oblíquo"
                        },
                        new
                        {
                            Id = new Guid("1b754f7c-9c5a-4588-9bef-9f5e3f90c847"),
                            MuscleGroupId = new Guid("ea069203-b519-4629-bee7-e7a07ad1f1b4"),
                            Name = "Abdominal máquina"
                        },
                        new
                        {
                            Id = new Guid("13ae2a63-6aca-4121-a695-442aa6bcae32"),
                            MuscleGroupId = new Guid("ea069203-b519-4629-bee7-e7a07ad1f1b4"),
                            Name = "Roda abdominal"
                        },
                        new
                        {
                            Id = new Guid("878f3614-314c-4ae0-b2ba-661603bcb2ed"),
                            MuscleGroupId = new Guid("ea069203-b519-4629-bee7-e7a07ad1f1b4"),
                            Name = "Elevação de pernas"
                        },
                        new
                        {
                            Id = new Guid("50337b37-bfe8-4c28-812b-04303e0ade06"),
                            MuscleGroupId = new Guid("8ce690bc-16ca-42aa-9d7e-bfab034a0d45"),
                            Name = "Agachamento livre"
                        },
                        new
                        {
                            Id = new Guid("cb9f7c31-bf89-4e5c-a56f-cb09a9b02eeb"),
                            MuscleGroupId = new Guid("8ce690bc-16ca-42aa-9d7e-bfab034a0d45"),
                            Name = "Agachamento hack"
                        },
                        new
                        {
                            Id = new Guid("9133e30b-2266-48d3-8c3c-e8939530a9fe"),
                            MuscleGroupId = new Guid("8ce690bc-16ca-42aa-9d7e-bfab034a0d45"),
                            Name = "Leg press"
                        },
                        new
                        {
                            Id = new Guid("9aa6274b-f9d0-476e-a61d-7823b7d8c4f4"),
                            MuscleGroupId = new Guid("8ce690bc-16ca-42aa-9d7e-bfab034a0d45"),
                            Name = "Cadeira extensora"
                        },
                        new
                        {
                            Id = new Guid("16404318-3ce7-4985-8225-b88531e9cbec"),
                            MuscleGroupId = new Guid("8ce690bc-16ca-42aa-9d7e-bfab034a0d45"),
                            Name = "Avanço"
                        },
                        new
                        {
                            Id = new Guid("bc82460d-8593-427f-b5be-6d21b8fe0534"),
                            MuscleGroupId = new Guid("8ce690bc-16ca-42aa-9d7e-bfab034a0d45"),
                            Name = "Agachamento búlgaro"
                        },
                        new
                        {
                            Id = new Guid("2e744094-0a81-433d-b91e-6dfec0a4129e"),
                            MuscleGroupId = new Guid("8ce690bc-16ca-42aa-9d7e-bfab034a0d45"),
                            Name = "Agachamento sumô"
                        },
                        new
                        {
                            Id = new Guid("3336862c-4599-4550-96bc-3df1a676576a"),
                            MuscleGroupId = new Guid("7d83b8be-8106-44c7-b757-21229c45a514"),
                            Name = "Mesa flexora"
                        },
                        new
                        {
                            Id = new Guid("37c2950d-e0cc-4ae7-902a-af172feea702"),
                            MuscleGroupId = new Guid("7d83b8be-8106-44c7-b757-21229c45a514"),
                            Name = "Cadeira flexora"
                        },
                        new
                        {
                            Id = new Guid("8e583585-d03a-445a-95e8-750ace7fc291"),
                            MuscleGroupId = new Guid("7d83b8be-8106-44c7-b757-21229c45a514"),
                            Name = "Stiff"
                        },
                        new
                        {
                            Id = new Guid("4fe825dc-180c-4a87-9740-8f37073b6290"),
                            MuscleGroupId = new Guid("7d83b8be-8106-44c7-b757-21229c45a514"),
                            Name = "Levantamento terra"
                        },
                        new
                        {
                            Id = new Guid("2cf92328-039f-4ca4-8f13-9144aeb525c0"),
                            MuscleGroupId = new Guid("7d83b8be-8106-44c7-b757-21229c45a514"),
                            Name = "Agachamento romeno"
                        },
                        new
                        {
                            Id = new Guid("3f05df30-9de0-4a7a-a7ce-03f9dc5b1547"),
                            MuscleGroupId = new Guid("4911e664-f75b-4f2a-92e0-6bbc9fcc6dec"),
                            Name = "Elevação pélvica"
                        },
                        new
                        {
                            Id = new Guid("23370ee4-ecb7-44fb-9ac7-d396999c7eca"),
                            MuscleGroupId = new Guid("4911e664-f75b-4f2a-92e0-6bbc9fcc6dec"),
                            Name = "Abdução de quadril"
                        },
                        new
                        {
                            Id = new Guid("7fe5beec-c495-4c38-b224-86e764e2fabe"),
                            MuscleGroupId = new Guid("4911e664-f75b-4f2a-92e0-6bbc9fcc6dec"),
                            Name = "Kick back glúteo"
                        },
                        new
                        {
                            Id = new Guid("2493a453-217e-4664-9f58-26b626825261"),
                            MuscleGroupId = new Guid("4911e664-f75b-4f2a-92e0-6bbc9fcc6dec"),
                            Name = "Hip thrust"
                        },
                        new
                        {
                            Id = new Guid("ad685077-ef96-4791-87bf-abc943e08424"),
                            MuscleGroupId = new Guid("51f00ebd-b28e-420c-a999-6f488a90362b"),
                            Name = "Panturrilha em pé"
                        },
                        new
                        {
                            Id = new Guid("461e26ea-41e6-4995-acea-b77c1449723a"),
                            MuscleGroupId = new Guid("51f00ebd-b28e-420c-a999-6f488a90362b"),
                            Name = "Panturrilha sentado"
                        },
                        new
                        {
                            Id = new Guid("361d1066-ec61-45bb-b014-33f2a84d87fd"),
                            MuscleGroupId = new Guid("51f00ebd-b28e-420c-a999-6f488a90362b"),
                            Name = "Panturrilha leg press"
                        },
                        new
                        {
                            Id = new Guid("cb544fd8-3ff2-477b-9e3d-06d64c39e0cc"),
                            MuscleGroupId = new Guid("78900b9b-e79a-47e0-8e6f-dd27da979fc9"),
                            Name = "Bom dia"
                        },
                        new
                        {
                            Id = new Guid("af73b55f-c8b7-459f-986b-5d78ab155eb3"),
                            MuscleGroupId = new Guid("78900b9b-e79a-47e0-8e6f-dd27da979fc9"),
                            Name = "Hiperextensão"
                        },
                        new
                        {
                            Id = new Guid("8d6a8087-26cf-4be4-ac1e-9e2da6ec50db"),
                            MuscleGroupId = new Guid("84d2a33c-3ff2-4698-85eb-860e0eeb1ee3"),
                            Name = "Encolhimento com barra"
                        },
                        new
                        {
                            Id = new Guid("f60ba848-8c83-40d3-ab75-2cb8a6a1e19d"),
                            MuscleGroupId = new Guid("84d2a33c-3ff2-4698-85eb-860e0eeb1ee3"),
                            Name = "Encolhimento com halteres"
                        },
                        new
                        {
                            Id = new Guid("b8d45ad1-1009-4cf9-b23d-c0db90bb6757"),
                            MuscleGroupId = new Guid("84d2a33c-3ff2-4698-85eb-860e0eeb1ee3"),
                            Name = "Remada alta"
                        },
                        new
                        {
                            Id = new Guid("3269c16e-92cb-4b8f-9ddb-9cd6d87f7ee8"),
                            MuscleGroupId = new Guid("c5fe59fb-e679-429a-ba23-57f4038675f4"),
                            Name = "Rosca de punho"
                        },
                        new
                        {
                            Id = new Guid("b881cf72-acc1-436b-8577-706fda53a38c"),
                            MuscleGroupId = new Guid("c5fe59fb-e679-429a-ba23-57f4038675f4"),
                            Name = "Rosca de punho invertida"
                        },
                        new
                        {
                            Id = new Guid("b638b4fb-deab-40b9-9c74-f52a6a0fe502"),
                            MuscleGroupId = new Guid("c5fe59fb-e679-429a-ba23-57f4038675f4"),
                            Name = "Farmer walk"
                        },
                        new
                        {
                            Id = new Guid("a883caac-92a1-4ef9-8ba0-95570375b59b"),
                            MuscleGroupId = new Guid("c5fe59fb-e679-429a-ba23-57f4038675f4"),
                            Name = "Rotação de punho"
                        },
                        new
                        {
                            Id = new Guid("13f20034-5142-49b4-94c2-dd997c372f9c"),
                            MuscleGroupId = new Guid("7d83b8be-8106-44c7-b757-21229c45a514"),
                            Name = "Agachamento smith"
                        },
                        new
                        {
                            Id = new Guid("494c023c-2223-4b25-b855-9a56c017b85d"),
                            MuscleGroupId = new Guid("7d83b8be-8106-44c7-b757-21229c45a514"),
                            Name = "Flexão nórdica"
                        },
                        new
                        {
                            Id = new Guid("13bf0b67-b1bb-4c1f-90b4-f80ce4dc76a5"),
                            MuscleGroupId = new Guid("c5fe59fb-e679-429a-ba23-57f4038675f4"),
                            Name = "Rosca inversa"
                        },
                        new
                        {
                            Id = new Guid("f0b74340-ca89-4429-9f3f-b1f6885dc5d7"),
                            MuscleGroupId = new Guid("4911e664-f75b-4f2a-92e0-6bbc9fcc6dec"),
                            Name = "Afundo"
                        },
                        new
                        {
                            Id = new Guid("82904538-0e45-4fd5-938b-8d54a63cdcdc"),
                            MuscleGroupId = new Guid("bd5b2d35-2696-4777-a49e-88ccdff78295"),
                            Name = "Puxada neutra"
                        },
                        new
                        {
                            Id = new Guid("9e41f367-e084-451e-a8a8-b8a805b47b5d"),
                            MuscleGroupId = new Guid("4e69d837-ae32-4272-9908-341963a08314"),
                            Name = "Face pull"
                        },
                        new
                        {
                            Id = new Guid("3790b237-943c-4898-94ad-bcc55d327dbd"),
                            MuscleGroupId = new Guid("7d83b8be-8106-44c7-b757-21229c45a514"),
                            Name = "Stiff unilateral"
                        });
                });

            modelBuilder.Entity("GymApp.Domain.Entities.ExerciseLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<double>("MaxWeight")
                        .HasColumnType("double precision");

                    b.Property<int>("RepsCompleted")
                        .HasColumnType("integer");

                    b.Property<int>("SetsCompleted")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkoutLogId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutLogId");

                    b.ToTable("ExerciseLogs");
                });

            modelBuilder.Entity("GymApp.Domain.Entities.MuscleGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MuscleGroups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1d1e3e9b-b392-4fe7-85f0-a3e709408b3c"),
                            Name = "Peitoral"
                        },
                        new
                        {
                            Id = new Guid("f8f48454-d0ef-4bcf-a75b-5be98be1b838"),
                            Name = "Bíceps"
                        },
                        new
                        {
                            Id = new Guid("9c4260d8-b1d6-4fd9-8dd4-b3ecae2f3dc7"),
                            Name = "Tríceps"
                        },
                        new
                        {
                            Id = new Guid("bd5b2d35-2696-4777-a49e-88ccdff78295"),
                            Name = "Dorsal"
                        },
                        new
                        {
                            Id = new Guid("ea069203-b519-4629-bee7-e7a07ad1f1b4"),
                            Name = "Abdômen"
                        },
                        new
                        {
                            Id = new Guid("8ce690bc-16ca-42aa-9d7e-bfab034a0d45"),
                            Name = "Quadríceps"
                        },
                        new
                        {
                            Id = new Guid("7d83b8be-8106-44c7-b757-21229c45a514"),
                            Name = "Posterior de Coxa"
                        },
                        new
                        {
                            Id = new Guid("4911e664-f75b-4f2a-92e0-6bbc9fcc6dec"),
                            Name = "Glúteo"
                        },
                        new
                        {
                            Id = new Guid("78900b9b-e79a-47e0-8e6f-dd27da979fc9"),
                            Name = "Lombar"
                        },
                        new
                        {
                            Id = new Guid("c5fe59fb-e679-429a-ba23-57f4038675f4"),
                            Name = "Antebraço"
                        },
                        new
                        {
                            Id = new Guid("4e69d837-ae32-4272-9908-341963a08314"),
                            Name = "Ombro"
                        },
                        new
                        {
                            Id = new Guid("51f00ebd-b28e-420c-a999-6f488a90362b"),
                            Name = "Panturrilha"
                        },
                        new
                        {
                            Id = new Guid("84d2a33c-3ff2-4698-85eb-860e0eeb1ee3"),
                            Name = "Trapézio"
                        });
                });

            modelBuilder.Entity("GymApp.Domain.Entities.Routine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Routines");
                });

            modelBuilder.Entity("GymApp.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GymApp.Domain.Entities.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoutineId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoutineId");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("GymApp.Domain.Entities.WorkoutExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxReps")
                        .HasColumnType("integer");

                    b.Property<int>("MinReps")
                        .HasColumnType("integer");

                    b.Property<int>("Sets")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutExercises");
                });

            modelBuilder.Entity("GymApp.Domain.Entities.WorkoutLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ExecutedAt")
                        .HasColumnType("date");

                    b.Property<Guid?>("WorkoutId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutLogs");
                });

            modelBuilder.Entity("GymApp.Domain.Entities.Exercise", b =>
                {
                    b.HasOne("GymApp.Domain.Entities.MuscleGroup", "MuscleGroup")
                        .WithMany("Exercises")
                        .HasForeignKey("MuscleGroupId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("MuscleGroup");
                });

            modelBuilder.Entity("GymApp.Domain.Entities.ExerciseLog", b =>
                {
                    b.HasOne("GymApp.Domain.Entities.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GymApp.Domain.Entities.WorkoutLog", "WorkoutLog")
                        .WithMany("ExercisesLogs")
                        .HasForeignKey("WorkoutLogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutLog");
                });

            modelBuilder.Entity("GymApp.Domain.Entities.Routine", b =>
                {
                    b.HasOne("GymApp.Domain.Entities.User", "User")
                        .WithMany("Routines")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymApp.Domain.Entities.Workout", b =>
                {
                    b.HasOne("GymApp.Domain.Entities.Routine", "Routine")
                        .WithMany("Workouts")
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Routine");
                });

            modelBuilder.Entity("GymApp.Domain.Entities.WorkoutExercise", b =>
                {
                    b.HasOne("GymApp.Domain.Entities.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GymApp.Domain.Entities.Workout", "Workout")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("GymApp.Domain.Entities.WorkoutLog", b =>
                {
                    b.HasOne("GymApp.Domain.Entities.Workout", "Workout")
                        .WithMany()
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("GymApp.Domain.Entities.MuscleGroup", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("GymApp.Domain.Entities.Routine", b =>
                {
                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("GymApp.Domain.Entities.User", b =>
                {
                    b.Navigation("Routines");
                });

            modelBuilder.Entity("GymApp.Domain.Entities.Workout", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("GymApp.Domain.Entities.WorkoutLog", b =>
                {
                    b.Navigation("ExercisesLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
